name: Build Check

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: martinlindhe/cmake-action@v1
        with:
          cmake-version: '3.26'

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Check if build succeeded
        run: |
          if [ $? -ne 0 ]; then
            echo "Build failed, preventing push"
            exit 1
          fi